<header>
  <div id="wrapper">
    <div id ="weatherAPI">
      <iframe src="APIweather/Weather.html"></iframe> 
    </div>
    <div class="google-map" style = "display: inline-block;">
        <iframe width="200" height="300" style="border: 2px black solid; margin-top: 2%; border-radius: 15px;" 
          src="https://www.google.com/maps/embed/v1/view?zoom=17&amp;center=41.6580%2C-83.6141&amp;key=AIzaSyC-ZmtYfG8N0eNFcuYLUDWx6_tARbDCjJo" allowfullscreen>
        </iframe>
        
      </div>	
    <nav id="main-navigation">
      <ul>
        <li style="float: left; color: white; padding-top: 6px; Font-weight: Bold; Font-size: 40px;">Coaster Coast</li><!--
        --><li><a href="index.html" class="others">HOME</a></li><!--
        --><li><a href="tickets.html" class="others">BUY TICKET / PASSES</a></li><!--
        --><li><a href="gallery.html" class="others">GALLERY / VIDEO</a></li><!--
        --><li><a href="https://maps.google.com/maps?ll=41.658,-83.6141&amp;z=17&amp;t=m&amp;hl=en-US&amp;gl=US&amp;mapclient=embed" class="others">MAP</a></li>
      </ul>
    </nav>
  </div>
</header>