<header>
  <div id="wrapper">
    <div id="weatherAPI">
      <iframe src="APIweather/Weather.html"></iframe> 
    </div>
    <div id="google-map">
      <iframe allowfullscreen
        src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJX4yyNDZEOogRBuopvdvVXG0&amp;key=AIzaSyC-ZmtYfG8N0eNFcuYLUDWx6_tARbDCjJo">
      </iframe>
    </div>	
    <nav id="main-navigation">
      <ul>
        <li id="nav-title">Coaster Coast</li><!--
        --><li><a href="index.html" class="others">HOME</a></li><!--
        --><li><a href="tickets.html" class="others">BUY TICKET / PASSES</a></li><!--
        --><li><a href="gallery.html" class="others">GALLERY / VIDEO</a></li><!--
        --><li><a href="https://maps.google.com/maps?ll=41.658,-83.6141&amp;z=17&amp;t=m&amp;hl=en-US&amp;gl=US&amp;mapclient=embed" class="others">MAP</a></li><!--
        --><li><a href="admin.html" class="others">LOGIN</a></li>
      </ul>
    </nav>
  </div>
</header>