<header>
    <div id="wrapper">
        <div id ="weatherAPI">
            <iframe src="APIweather/Weather.html"></iframe> 
        </div>
        <nav id="main-navigation">
            <ul>
      <li style="float: left; color: white; padding-top: 6px; Font-weight: Bold; Font-size: 40px;">Coaster Coast</li>
      <li><a href="index.html" class="current">HOME</a></li>
      <li><a href="tickets.html" class="others">BUY TICKET / PASSES</a></li>
      <li><a href="gallery.html" class="others">GALLERY / VIDEO</a></li>
      <li><a href="map.html" class="others">MAP</a></li>
            </ul>
        </nav>
    </div>
</header>